### ISSUE TITLE
Team to Discuss Definition of Done:

### ISSUE THREAD

**Issue by 19mderose** [18F/gsa-small-business-experience#38]
As a team we need to ensure our we meet our guideline for DOD so that we  complete each task.
- Code Scanning and Review
-Non- Functional Requirements-Stakeholder (OSDBU)
-Design/UX Review
- GSA Goal- OMB Circular Guide.
-Stakeholder Review: Demo.
-Documentation is updated.

**Comment by cmajel** [comment]
Reviving this since. What's been working for you all so far? 

On past projects, I've found sometimes a fully checked off task list means something is "done", or the team may create a "we'll know we're done when" list of specific tasks that show this is complete. (things like this is reviewed by another team member, files are linked to this issue, a meeting is held etc).

**Comment by jduss4** [comment]
Honestly, I think we haven't really been using this closely.  Here's what we ultimately came up with:

1. Code Scanning and review
1. Design / UX Review
1. Documentation updated
1. Meets administration goals and priorities
1. Business / stakeholder review (demo) (GSA A-suite and OSDBU)

It seems to me more like this definition of done is more appropriate for what we've been considering "milestones," or groups of stories, rather than individual issues / stories / tasks?
